preserve_hierarchy: true

files:
  - source: /src/lang/en_US/data.json
    translation: /src/data/%locale_with_underscore%/data.json
  - source: /src/lang/en_US/meta.json
    translation: /src/data/%locale_with_underscore%/meta.json
