files:
  - source: /front/src/lang/en_US.json
    translation: /front/src/lang/%locale_with_underscore%.json
  - source: /front/src/lang/zh_CN.json
    translation: /front/src/lang/%locale_with_underscore%.json
